# -*- coding: utf-8 -*-
"""agent pharmaceutique.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12o0k0haP4oBzreUmUZYeNx2QxfNap4t3
"""

import requests
def get_drug_label(drug_name: str):
  """on va recuperer les infos de ce med depuis openFDA"""
  url = "https://api.fda.gov/drug/label.json"
  params={
      "search":f"openfda.generic_name:{drug_name}",
      "limit" : 1
  }
  response=requests.get(url,params=params)
  if response.status_code==200:
    return response.json()
  else:
    print(f"ERROR!{response.status_code}")
    return None
result=get_drug_label("metformin")
print(result)

def extract_drug_info(raw_data):
    """Extrait uniquement les champs qui nous intéressent de la réponse openFDA."""
    if raw_data is None:
      return None
    elem1=raw_data["results"][0]
    #elem1=raw_data["results"][0]["drug_interactions"]
    med_info={
         "name": elem1["openfda"]["generic_name"][0],
         "side_effects":None if len(elem1.get("adverse_reactions",[]))==0 else elem1.get("adverse_reactions")[0],
         #"interactions": elem1["drug_interactions"][0] if elem1["drug_interactions"] else None
         #Pour eviter le crash de KeyError au cas ou la cle n'est meme pas presente dans le dict elem1 on opte pour la solution .get()
         #Dans le cas où la clé n'existe pas ca renvoie le None,valeur par defaut de la fct° get()
         #si on veut forcer ce qu'on affiche dans ce cas au lieu du None on ajoute par exemple get("k",[])
         #Sauf que on veut aussi eviter que ca nous renvoie tout la liste car e veut juste le 1er element d'où la condition
         "interactions": None if len(elem1.get("drug_interactions",[]))==0  else elem1.get("drug_interactions")[0]

    }
    return med_info
result2=extract_drug_info(result)
print(result2)
"""Tu veux mettre dans med_info["interactions"] soit du texte (le premier élément de la liste), soit None si vraiment il n'y a rien à afficher.
Mais une liste vide [] n'est ni l'un ni l'autre :
Avec ce code seul, med_info["interactions"] peut valoir [] (une liste vide), jamais un texte tout seul ni None.
Si Gemini reçoit [] à la place d'un texte, ça reste bizarre à traiter à l'étape 3."""

result_ibu = get_drug_label("ibuprofen")
elem1_ibu = result_ibu["results"][0]
print(elem1_ibu.keys())

from google.colab import userdata
# To access your Gemini API key, ensure it is saved in the Colab secrets manager
# under the name 'GOOGLE_API_KEY' (or the specific name you used).
# You can access the secrets manager via the '🔑' icon in the left sidebar.
GOOGLE_API_KEY = userdata.get('GEMINI_API_KEY')
print("Secret retrieved successfully!") # Optional: to confirm retrieval

!pip install -q google-genai

from google.colab import userdata
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

from google import genai

client=genai.Client(api_key=GEMINI_API_KEY)
def summarize_drug_info(med_info):
  if med_info is None:
    return None
  if med_info["side_effects"] is None:
    return f"Aucune information sur les effets secondaires n'est disponible pour {med_info['name']}."
  prompt=f"""resume les informations sur les effets indesirables '{med_info["side_effects"]}' du medicament '{med_info['name']}' en 4 phrases en français simple, sans jargon médical. Base-toi uniquement sur le texte suivant, n'ajoute aucune information qui n'y figure pas"""
  response=client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=prompt
   )

  return response.text
med_=get_drug_label("Metformin")
med_plus=extract_drug_info(med_)
res=summarize_drug_info(med_plus)
print(res)

from google.genai import types
from google import genai

def ask_agent(question):

    config = types.GenerateContentConfig(tools=[get_drug_label])

    response =client.models.generate_content (
        model="gemini-3.1-flash-lite",
        contents=question ,
        config=config
    )

    if response.function_calls:

        call = response.function_calls[0]
        drug_name_found = call.args["drug_name"]
        print(f" L'agent a identifié le médicament : {drug_name_found}")

        raw_data = get_drug_label(drug_name_found)
        med_info = extract_drug_info(raw_data)

        return summarize_drug_info(med_info)

    else:
        return response.text
reponse_finale = ask_agent("Peux-tu me donner les effets secondaires de l'Ibuprofen ?")
print(reponse_finale)